title: KASHTANOVA Victoriya
logo: /assets/img/my_logo.png
head_img: /img/face.png
email: "kashtanovavictoriya@gmail.com"
cv: /assets/pdfs/CV.pdf
# researchgate: https://www.researchgate.net/profile/Victoriya_Kashtanova2/research
googlescholar: https://scholar.google.com/citations?hl=en&user=SPg6dvUAAAAJ
linkedin: https://www.linkedin.com/in/victoriya-kashtanova/
theme: jekyll-theme-minimal
