title: KASHTANOVA Victoriya
logo: ./_assets/img/my_logo.png
head_img: ./_assets/img/face.png
email: "kashtanovavictoriya@gmail.com"
cv: ./_assets/pdfs/CV.pdf
googlescholar: https://scholar.google.com/citations?hl=en&user=SPg6dvUAAAAJ
linkedin: https://www.linkedin.com/in/victoriya-kashtanova/
