title: KASHTANOVA Victoriya
logo: /assets/img/my_logo.png
head_img: /img/face.png
email: "kashtanovavictoriya@gmail.com"
cv: /assets/pdfs/CV.pdf
# researchgate: https://www.researchgate.net/profile/Victoriya_Kashtanova2/research
googlescholar: https://scholar.google.com/citations?hl=en&user=SPg6dvUAAAAJ&sortby=pubdate&view_op=list_works&citft=1&citft=2&email_for_op=KashtanovaVictoriya%40gmail.com&authuser=1&gmla=AJsN-F7ObWBSJdRSghNTCIHQPWwYCJFdKoA4WY0vX469tUfduNPR5NgpTk54pqsoaWZjVkRos-pHQw3ZIKkdayDdGiNTY_YRPBOg93rBc6AnjORzhIfuaJzkJqyQnJfRhBFcV1YWMgFX6vfajLIQNi6me4XO-Nl52xWcJVxiCR6BznArqhPyxOAkS9gNtue-S6zJ2GfP40k0__TYQLWzG7220N8PRp2LDUqj6JnNUI_ApehxHeK-aCWIeXfC3KooslU_Px8dzfuRKsuEuZQzF1jkqpUR0jsEtFDuXkr92LOYfUjbYsEBI9_k-qCb-l8ujkxMvfjYDwoywvaCiTET_cJ5AhgvBvTGvw
linkedin: https://www.linkedin.com/in/victoriya-kashtanova/
theme: jekyll-theme-minimal
