title: KASHTANOVA Victoriya
logo: /assets/img/my_logo.png
email: "victoriya.kashtanova@eleves.enpc.fr"
cv: /assets/pdfs/CV.pdf
researchgate: https://www.researchgate.net/profile/Victoriya_Kashtanova2/research
linkedin: https://www.linkedin.com/in/victoriya-kashtanova/
theme: jekyll-theme-minimal
